#!/bin/bash

#
# Goes through all source javascripts that we need to be able
# to copy into a packages directory
#
JSFILE=$1
echo "Starting conversion.."
touch $JSFILE
echo "//This file is generated by makeb64vars-win32.sh" > $JSFILE
cmd.exe /c makeb64js-all-win32.bat
#Run combination script..